// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YellowCarrotDb.Data;

#nullable disable

namespace YellowCarrotDb.Migrations.RecipeDb
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20221215103619_Initial2")]
    partial class Initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.Property<int>("RecipesRecipeId")
                        .HasColumnType("int");

                    b.Property<int>("TagsTagId")
                        .HasColumnType("int");

                    b.HasKey("RecipesRecipeId", "TagsTagId");

                    b.HasIndex("TagsTagId");

                    b.ToTable("RecipeTag");

                    b.HasData(
                        new
                        {
                            RecipesRecipeId = 1,
                            TagsTagId = 1
                        },
                        new
                        {
                            RecipesRecipeId = 1,
                            TagsTagId = 2
                        },
                        new
                        {
                            RecipesRecipeId = 2,
                            TagsTagId = 2
                        },
                        new
                        {
                            RecipesRecipeId = 2,
                            TagsTagId = 3
                        });
                });

            modelBuilder.Entity("YellowCarrotDb.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            IngredientName = "Eggs",
                            Quantity = 2.0,
                            RecipeId = 1,
                            Unit = "pcs"
                        },
                        new
                        {
                            IngredientId = 2,
                            IngredientName = "Milk",
                            Quantity = 4.0,
                            RecipeId = 1,
                            Unit = "dl"
                        },
                        new
                        {
                            IngredientId = 3,
                            IngredientName = "Flour",
                            Quantity = 2.0,
                            RecipeId = 1,
                            Unit = "dl"
                        },
                        new
                        {
                            IngredientId = 4,
                            IngredientName = "Salt",
                            Quantity = 0.5,
                            RecipeId = 1,
                            Unit = "tbs"
                        },
                        new
                        {
                            IngredientId = 5,
                            IngredientName = "Sausage",
                            Quantity = 4.0,
                            RecipeId = 2,
                            Unit = "pcs"
                        },
                        new
                        {
                            IngredientId = 6,
                            IngredientName = "Buns",
                            Quantity = 4.0,
                            RecipeId = 2,
                            Unit = "pcs"
                        });
                });

            modelBuilder.Entity("YellowCarrotDb.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            Name = "Pancakes",
                            Username = "user"
                        },
                        new
                        {
                            RecipeId = 2,
                            Name = "Hot dogs",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("YellowCarrotDb.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Name = "Vegetarian"
                        },
                        new
                        {
                            TagId = 2,
                            Name = "Fast-food"
                        },
                        new
                        {
                            TagId = 3,
                            Name = "Meat"
                        },
                        new
                        {
                            TagId = 4,
                            Name = "Fish"
                        },
                        new
                        {
                            TagId = 5,
                            Name = "Vegan"
                        },
                        new
                        {
                            TagId = 6,
                            Name = "Egg-free"
                        },
                        new
                        {
                            TagId = 7,
                            Name = "Gluten-free"
                        },
                        new
                        {
                            TagId = 8,
                            Name = "Keto"
                        },
                        new
                        {
                            TagId = 9,
                            Name = "Healthy"
                        });
                });

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.HasOne("YellowCarrotDb.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YellowCarrotDb.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YellowCarrotDb.Models.Ingredient", b =>
                {
                    b.HasOne("YellowCarrotDb.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("YellowCarrotDb.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
